#!/bin/sh

## hyphop ##

#= make aml-burn-images VIM1 VIM2 VIM3 VIM3L


PR=$(dirname $0)
RP=$(realpath $PR)

cd "$PR" || exit 1

. ./build.conf

[ "$BOARDS" ] || BOARDS="$@"
[ "$BOARDS" ] || \
BOARDS="VIM1 VIM2 VIM3 VIM3L"


for BOARD in $BOARDS ; do

    UBOOT="$UBOOT_DIR2/$BOARD.$UBOOT_SD_MMC0"

    [ -s $UBOOT ] || {
	echo "[e] $UBOOT not found"
	exit 1
    }
done

export UBOOT_VIM1="$UBOOT_DIR2/VIM1.$UBOOT_SD_MMC0"
export UBOOT_VIM2="$UBOOT_DIR2/VIM2.$UBOOT_SD_MMC0"
export UBOOT_VIM3="$UBOOT_DIR2/VIM3.$UBOOT_SD_MMC0"
export UBOOT_VIM3L="$UBOOT_DIR2/VIM3L.$UBOOT_SD_MMC0"
export UBOOT_VIM1_SPI="$UBOOT_DIR2/VIM1.$UBOOT_SPI"
export UBOOT_VIM2_SPI="$UBOOT_DIR2/VIM2.$UBOOT_SPI"
export UBOOT_VIM3_SPI="$UBOOT_DIR2/VIM3.$UBOOT_SPI"
export UBOOT_VIM3L_SPI="$UBOOT_DIR2/VIM3L.$UBOOT_SPI"

../../khadas-rescue-tools/projects/UBOOT.mainline.krescue/make && \
    cp /tmp/VIMx.UBOOT.mainline.emmc.kresq $UBOOT_DIR2
